(function(root){
  const V=root.VIVA,U=V.ui;
  V.features=V.features||{};
  V.features.home=function(){
    const s=V.store.state, due=U.weak().slice(0,5), mins=s.studyLog[V.store.today()]||0, goal=Math.min(100,Math.round(mins/s.goal*100));
    return `<div class="hero"><section class="card hero-main"><div class="kicker">VIVA · adaptive Spanish game</div><h1>Your Spanish<br>has a memory.</h1><p>VIVA tracks what you forget, how you misspell, how fast you recall, which abilities are weak, and when English should disappear. It builds a model of <b>your Spanish</b>, not just a streak.</p><div class="actions"><button class="btn primary" data-route="journey">${U.learned()?"Resume journey":"Start with Hola"}</button><button class="btn secondary" data-route="coach">Smart review</button><button class="btn ghost" data-route="story">Story world</button></div></section><aside class="card hero-side"><div class="ring" style="--deg:${goal*3.6}deg"><div><b>${goal}%</b><span>daily goal</span></div></div><div class="triple"><div class="mini"><b>${U.learned()}</b><span>phrases</span></div><div class="mini"><b>${U.strong()}</b><span>strong</span></div><div class="mini"><b>${s.streak||0}</b><span>streak</span></div></div><div class="muted" style="text-align:center;font-size:10px">${mins} / ${s.goal} minutes today</div></aside></div>
    <section class="section"><div class="section-head"><div><h2>Adaptive plan</h2><p>Generated from what is weak right now.</p></div></div><div class="card plan">${[['learn','Learn 2 new phrases','New material','4 min'],['review','Repair weak memory',`${due.length||3} due`,'3 min'],['listen','No-caption listening','Audio only','2 min'],['mission','Use it in context','Real-world mission','3 min']].map(([id,t,d,m])=>`<div class="task ${s.daily[id]?'done':''}" data-task="${id}"><button class="check">${s.daily[id]?'✓':''}</button><div><b>${t}</b><small>${d}</small></div><span class="mins">${m}</span></div>`).join('')}</div></section>
    <section class="section"><div class="section-head"><div><h2>Signature systems</h2><p>The things that make VIVA its own game.</p></div></div><div class="grid-4">${[
      ['🧬','Memory DNA','Learns your personal error patterns and recall speed.','coach','Personal'],['🫥','Caption Fade','English disappears phrase-by-phrase as memory becomes reliable.','journey','Adaptive'],['🎭','Life Missions','Unlock abilities like ordering, meeting people, and getting un-lost.','labs','Real-world'],['🧯','Rescue Mode','Train what to say when you freeze or understand nothing.','labs','Survival'],['🔁','Shadow Loop','Hear, repeat, record, replay, compare rhythm.','labs','Speaking'],['🧩','Sentence Forge','Build new sentences only from language you have earned.','labs','Generation'],['📡','Forgetting Radar','Predicts which phrases are slipping and brings them back.','coach','Predictive'],['🪪','Spanish Passport','Collect capability stamps, not meaningless XP.','passport','Progress'],['🌆','Story World','Story chapters unlock only when your language is ready.','story','Narrative'],['⚡','Pressure Mode','Tests when knowledge becomes automatic.','labs','Speed'],['🧰','Personal Missions','Turn phrases from your real life into lessons.','vault','Personal'],['🎧','Conversation Ladder','Conversations grow only from words you actually know.','labs','Interactive']
    ].map(x=>U.feature(...x)).join('')}</div></section>
    <section class="section grid-2"><div class="card panel"><h3>Forgetting radar</h3>${due.length?due.map(w=>U.wordRow(w)).join(''):'<div class="feedback">Nothing weak yet. Start the first lesson.</div>'}</div><div class="card panel"><h3>Survival readiness</h3>${['Greet','Meet People','Order','Directions','Survive'].map(sk=>`<div style="margin:11px 0"><div style="display:flex;justify-content:space-between;font-size:11px"><span>${sk}</span><b>${U.skillScore(sk)}%</b></div><div class="progress"><i style="width:${U.skillScore(sk)}%"></i></div></div>`).join('')}</div></section>`;
  };
})(typeof globalThis!=="undefined"?globalThis:window);