(function(root){
  const V=root.VIVA,U=V.ui;
  V.features=V.features||{};
  V.features.home=function(){
    const s=V.store.state,due=U.weak().slice(0,5),mins=s.studyLog[V.store.today()]||0,goal=Math.min(100,Math.round(mins/s.goal*100)),profile=V.brain.profile(s,V.content.phrases),adventure=s.dailyAdventureDone===V.store.today();
    return `<div class="hero"><section class="card hero-main"><div class="kicker">VIVA · language world</div><h1>Learn Spanish<br>by living in it.</h1><p>Your course, Madrid world, NPCs, review queue, captions, missions, stories and daily adventure all read from the same learner model. The game changes because <b>you</b> changed.</p><div class="actions"><button class="btn primary" data-route="journey">${U.learned()?'Resume journey':'Start with Hola'}</button><button class="btn secondary" data-route="world">Enter Madrid</button><button class="btn ghost" data-route="coach">Open VIVA Brain</button></div></section><aside class="card hero-side"><div class="ring" style="--deg:${goal*3.6}deg"><div><b>${goal}%</b><span>daily goal</span></div></div><div class="triple"><div class="mini"><b>${U.learned()}</b><span>phrases</span></div><div class="mini"><b>${U.strong()}</b><span>strong</span></div><div class="mini"><b>${s.streak||0}</b><span>streak</span></div></div><div class="muted" style="text-align:center;font-size:10px">${mins} / ${s.goal} minutes · ${V.world.accents[s.settings.accent]?.flag||'🇪🇸'} ${V.world.accents[s.settings.accent]?.name||'Spain'}</div></aside></div>
    <section class="section"><div class="section-head"><div><h2>Today’s generated adventure</h2><p>Built from weak memory + real-life context.</p></div></div><div class="card adventure-banner"><div><span class="adventure-icon">${adventure?'✓':'🌆'}</span><div><b>${adventure?'Adventure complete':'Madrid throws you a problem'}</b><p>${adventure?'Tomorrow gets a different mix.':'Open the city and solve the daily dynamic event using phrases your brain needs today.'}</p></div></div><button class="btn ${adventure?'ghost':'primary'}" data-route="world">${adventure?'Visit Madrid':'Play adventure'}</button></div></section>
    <section class="section"><div class="section-head"><div><h2>Adaptive plan</h2><p>Generated from what is weak right now.</p></div><span class="badge">Brain says: ${V.brain.recommend(s,V.content.phrases).join(' · ')}</span></div><div class="card plan">${[['learn','Learn 2 new phrases','New material','4 min'],['review','Repair weak memory',`${due.length||3} due`,'3 min'],['listen','No-caption listening','Audio only','2 min'],['mission','Use it in context','Real-world mission','3 min']].map(([id,t,d,m])=>`<div class="task ${s.daily[id]?'done':''}" data-task="${id}"><button class="check">${s.daily[id]?'✓':''}</button><div><b>${t}</b><small>${d}</small></div><span class="mins">${m}</span></div>`).join('')}</div></section>
    <section class="section"><div class="section-head"><div><h2>20 systems, one game</h2><p>Not twenty random tabs. Every system shares your learner state.</p></div></div><div class="grid-4">${[
      ['🧠','VIVA Brain','Personal learner model and recommendations.','coach','Core'],['💬','AI NPCs','Open conversation with a local smart fallback.','world','Conversation'],['🎙️','Pronunciation Engine','Speech recognition, shadowing and replay.','labs','Speaking'],['🌆','Madrid World','A city that opens with language ability.','world','World'],['🧑‍🤝‍🧑','NPC Memory','Characters remember facts, turns and relationships.','world','Memory'],['🎲','Dynamic Events','Unexpected problems adapted to your level.','world','World'],['🧰','Teach From My Life','Turn interests into a personal curriculum.','vault','Personal'],['📱','Real World Scanner','Photo → phrase → personal lesson.','labs','Real world'],['🎞️','Immersion Feed','Short audio-first cards with optional reveal.','labs','Listening'],['🕵️','Detective Mode','Use Spanish clues to solve cases.','labs','Game'],['👑','Boss Conversations','Longer conversations with limited rescue help.','labs','Boss'],['📡','Forgetting Prediction','Risk scores decide what returns next.','coach','Predictive'],['🧩','Five-Way Repair','One mistake retrained through five memory routes.','coach','Repair'],['❓','Why Button','Explain chunks exactly when curiosity appears.','journey','Explain'],['🧬','Grammar Discovery','Notice the pattern before learning its name.','labs','Grammar'],['🌍','Accent Studio','Spain, Mexico, Argentina and Colombia.','labs','Audio'],['🏁','Survival Test','A five-stage real-world gauntlet.','labs','Test'],['🪪','Ability Passport','Ready / Almost / Developing by real skill.','passport','Progress'],['📖','Campaign','A 12-chapter Madrid progression.','story','Narrative'],['✨','Daily Adventure','A changing micro-event every day.','world','Daily']
    ].map(x=>U.feature(...x)).join('')}</div></section>
    <section class="section grid-2"><div class="card panel"><h3>Forgetting radar</h3>${due.length?due.map(w=>`<div class="error-row"><div><b>${w.es}</b><small>${w.en} · risk ${V.brain.forgettingRisk(w.es,s)}%</small><div class="progress"><i style="width:${V.brain.forgettingRisk(w.es,s)}%"></i></div></div><button class="pill" data-speak="${U.esc(w.es)}">🔊</button></div>`).join(''):'<div class="feedback">Nothing weak yet. Start the first lesson.</div>'}</div><div class="card panel"><h3>Memory DNA snapshot</h3><div class="coach-note">Dominant friction: <b>${profile.errorType}</b><br>Best observed mode: <b>${profile.bestMode}</b></div>${['Greet','Meet People','Order','Directions','Survive'].map(sk=>`<div style="margin:11px 0"><div style="display:flex;justify-content:space-between;font-size:11px"><span>${sk}</span><b>${V.brain.abilityStatus(U.skillScore(sk))}</b></div><div class="progress"><i style="width:${U.skillScore(sk)}%"></i></div></div>`).join('')}</div></section>`;
  };
  V.features.bindHome=function(){U.bindSpeak();};
})(typeof globalThis!=='undefined'?globalThis:window);
