(function(root){
  const V=root.VIVA,U=V.ui;
  function lessonList(){ const s=V.store.state; return V.content.lessons.map((l,i)=>`<button class="lesson-item ${i===s.lesson?'active':''} ${!U.lessonUnlocked(i)?'locked':''}" data-lesson="${i}" ${!U.lessonUnlocked(i)?'disabled':''}><b>${i+1}. ${l.title}</b><small>${!U.lessonUnlocked(i)?'Locked':U.lessonPct(i)+'% mastery'} · ${l.desc}</small></button>`).join(''); }
  function practice(){
    const s=V.store.state,l=V.content.lessons[s.lesson],w=U.phrase(l.words[s.lessonIndex%l.words.length]); if(!w)return '';
    const fade=U.mastery(w.es)>=s.settings.captionFade;
    if(s.phase==='teach') return `<div class="stage">Learn</div><div class="big-es">${w.es}</div>${fade?'<div class="feedback close" style="text-align:center">Caption faded. Your memory says this phrase is strong enough.</div>':`<div class="big-en">${w.en}</div>`}<div class="pron">${w.pron}</div><div class="actions" style="justify-content:center"><button class="btn secondary" data-speak="${U.esc(w.es)}">🔊 Hear</button><button class="btn ghost" id="slowHear">🐢 Slow</button>${fade?'<button class="btn ghost" id="revealEnglish">Reveal English</button>':''}<button class="btn ghost" id="whyPhrase">Why?</button></div><div class="feedback">Say it twice. Then VIVA removes the answer and tests recall.</div><div class="actions"><button class="btn primary" id="saidIt">I said it</button></div><div class="footerline"><span>${w.skill}</span><span>${U.mastery(w.es)}% mastery</span></div>`;
    if(s.phase==='recall') return `<div class="stage">Recall</div><div class="prompt">Type the Spanish for:<br><span style="color:var(--gold)">${w.en}</span></div><div class="subprompt">No answer caption. Near-misses get coached instead of punished.</div><div class="answer-row"><input class="input" id="recallInput" autocapitalize="none" autocomplete="off" spellcheck="false"><button class="btn primary" id="recallCheck">Check</button></div><div id="recallFeedback"></div><div class="actions"><button class="btn ghost" id="recallHint">Hint</button><button class="btn ghost" data-speak="${U.esc(w.es)}">Hear it</button><button class="btn ghost" id="whyPhrase">Why?</button></div><div class="footerline"><span>${w.es}</span><span>${U.mastery(w.es)}%</span></div>`;
    const opts=U.shuffle([w,...V.content.phrases.filter(x=>x.es!==w.es).slice(0,3)]);
    return `<div class="stage">Listen</div><div class="prompt">Which Spanish phrase did you hear?</div><div class="subprompt">Audio first. Reading second.</div><div class="actions"><button class="btn secondary" data-speak="${U.esc(w.es)}">🔊 Play</button><button class="btn ghost" id="slowHear">Slow</button></div><div class="choice-grid">${opts.map(o=>`<button class="choice" data-listen-answer="${U.esc(o.es)}">${o.es}</button>`).join('')}</div><div id="listenFeedback"></div><div class="footerline"><span>Listening</span><span>${U.mastery(w.es)}%</span></div>`;
  }
  V.features=V.features||{};
  V.features.journey=function(){ return `<div class="page-head"><div><h1>Journey</h1><p>Learn → recall → listen → use. Captions fade as memory gets stronger.</p></div><div class="actions"><button class="btn ghost" data-route="coach">Review weak words</button></div></div><div class="journey-layout"><aside class="card lesson-list">${lessonList()}</aside><section class="card practice" id="practiceMount">${practice()}</section></div><section class="section"><div class="card panel"><div class="section-head"><div><h2>Knowledge map</h2><p>Your actual abilities, not chapter numbers.</p></div></div><div class="skill-grid">${['Greet','Politeness','Meet People','Ask','Order','Survive','Directions','Shopping'].map(sk=>`<div class="skill"><b>${sk}</b><span>${U.skillScore(sk)}% ready</span><div class="progress"><i style="width:${U.skillScore(sk)}%"></i></div></div>`).join('')}</div></div></section>`; };
  V.features.bindJourney=function(){
    const s=V.store.state,l=V.content.lessons[s.lesson],w=U.phrase(l.words[s.lessonIndex%l.words.length]);
    document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{ s.lesson=+b.dataset.lesson; s.lessonIndex=0; s.phase='teach'; V.store.save(); V.app.render(); });
    U.bindSpeak(); const slow=document.getElementById('slowHear'); if(slow) slow.onclick=()=>V.audio.speak(w.es,true);
    const reveal=document.getElementById('revealEnglish'); if(reveal) reveal.onclick=()=>{ reveal.outerHTML=`<div class="feedback">${w.en}</div>`; }; const why=document.getElementById('whyPhrase'); if(why) why.onclick=()=>U.modal(`<div class="modal-head"><h2>Why? · ${w.es}</h2><button class="close" data-close>×</button></div><div class="coach-note">${V.brain.why(w.es)}</div>`);
    const said=document.getElementById('saidIt'); if(said) said.onclick=()=>{ s.seen[w.es]=(s.seen[w.es]||0)+1; s.mastery[w.es]=Math.max(s.mastery[w.es]||0,15); s.phase='recall'; s._started=Date.now(); V.store.save(); V.app.render(); };
    const check=document.getElementById('recallCheck'); if(check){ const input=document.getElementById('recallInput'); const run=()=>{ const result=V.answerAnalyzer.analyze(input.value,w.es,{strictAccents:s.settings.strictAccents}); const ms=Date.now()-(s._started||Date.now()); if(result.correct){ V.coachEngine.record(w.es,result,ms); document.getElementById('recallFeedback').innerHTML=`<div class="feedback good"><b>${result.title}</b> ${result.message}${ms<5000?' Fast recall too.':''}</div>`; s.phase='listen'; V.store.save(); setTimeout(()=>V.app.render(),650); } else { V.coachEngine.record(w.es,result,ms); document.getElementById('recallFeedback').innerHTML=`<div class="feedback ${result.close?'close':'bad'}"><b>${result.title}</b> ${result.message}</div>`; input.focus(); input.select(); } }; check.onclick=run; input.onkeydown=e=>{if(e.key==='Enter')run()}; setTimeout(()=>input.focus(),40); document.getElementById('recallHint').onclick=()=>{ document.getElementById('recallFeedback').innerHTML=`<div class="feedback close">Starts with <b>${w.es[0]}</b> · ${w.es.split(' ').length} word${w.es.split(' ').length>1?'s':''} · ${w.pron}</div>`; }; }
    document.querySelectorAll('[data-listen-answer]').forEach(b=>b.onclick=()=>{ const correct=b.dataset.listenAnswer===w.es; s.attempts++; if(correct){ s.correct++; b.classList.add('good'); s.mastery[w.es]=V.mastery.clamp((s.mastery[w.es]||0)+V.mastery.gain(s.mastery[w.es]||0,'listen',5000)); s.phase='teach'; s.lessonIndex++; s.daily.learn=true; V.store.study(); V.store.save(); setTimeout(()=>{ if(s.lessonIndex>=l.words.length){s.lessonIndex=0;V.ui.toast('Lesson cycle complete.')} V.app.render(); },520); } else { b.classList.add('bad'); s.errors[w.es]=(s.errors[w.es]||0)+1; document.getElementById('listenFeedback').innerHTML='<div class="feedback bad">Not that one. Replay the audio and compare the rhythm.</div>'; V.store.save(); } });
    if(s.phase==='teach' && s.settings.autoAudio) setTimeout(()=>V.audio.speak(w.es),140); if(s.phase==='listen') setTimeout(()=>V.audio.speak(w.es),160);
  };
})(typeof globalThis!=="undefined"?globalThis:window);