(function(root){
  const V=root.VIVA,U=V.ui;
  const cards=[
    ['🎭','Life Missions','Practice abilities instead of vocabulary lists.','missions'],['🧯','Rescue Mode','Train what to say when you freeze.','rescue'],['🎧','Dictation Studio','Hear it and type it.','dictation'],['🎙️','Pronunciation Engine','Speech recognition and targeted feedback.','pronunciation'],['🔁','Shadow Loop','Hear → repeat → record → replay.','shadow'],['🧩','Sentence Forge','Build sentences from earned pieces.','builder'],['⚡','Pressure Mode','Test automatic recognition.','pressure'],['🔗','Match Sprint','Rapid Spanish ↔ English pairing.','matching'],['💬','AI Conversation','Adaptive NPC chat with local fallback.','conversation'],['🧠','One Mistake, Five Ways','Repair one weak phrase through five memory paths.','repair'],['📱','Real World Scanner','Turn a photo, sign, or menu phrase into practice.','scanner'],['🎞️','Immersion Feed','Short no-caption audio cards tuned to your level.','feed'],['🕵️','Detective Mode','Read Spanish clues and solve a mystery.','detective'],['👑','Boss Conversation','A longer conversation with limited rescue help.','boss'],['🧬','Grammar Discovery','Notice patterns before VIVA names the rule.','grammar'],['🌍','Accent Studio','Spain, Mexico, Argentina, Colombia.','accents'],['🏁','Survival Test','Airport → Metro → Café → People → Problem.','survival'],['🌆','No-Caption Day','A chained Spanish-only challenge.','nocaption']
  ];
  V.labModes=V.labModes||{};V.features=V.features||{};

  V.labModes.matching=()=>{const pool=U.shuffle(V.content.phrases.slice(0,6));let sel=null;document.getElementById('labMount').innerHTML=`<div class="card game"><h3>🔗 Match Sprint</h3><div class="match"><div class="match-col">${U.shuffle(pool).map(w=>`<button class="match-btn left" data-es="${U.esc(w.es)}">${w.es}</button>`).join('')}</div><div class="match-col">${U.shuffle(pool).map(w=>`<button class="match-btn right" data-es="${U.esc(w.es)}">${w.en}</button>`).join('')}</div></div><div id="matchFb"></div></div>`;document.querySelectorAll('.left').forEach(x=>x.onclick=()=>{document.querySelectorAll('.left').forEach(y=>y.classList.remove('sel'));x.classList.add('sel');sel=x;});document.querySelectorAll('.right').forEach(x=>x.onclick=()=>{if(!sel)return;if(sel.dataset.es===x.dataset.es){sel.classList.add('done');x.classList.add('done');sel=null;document.getElementById('matchFb').innerHTML='<div class="feedback good">Match.</div>';}else document.getElementById('matchFb').innerHTML='<div class="feedback bad">Those do not match.</div>';});};

  V.features.labs=()=>`<div class="page-head"><div><h1>Labs</h1><p>Different training rooms for the same language. Your mistakes decide which ones matter most.</p></div><span class="badge">${V.brain.recommend(V.store.state,V.content.phrases).join(' · ')}</span></div><div class="section" id="labMount" tabindex="-1"></div><div class="lab-grid">${cards.map(([i,t,p,id])=>`<button class="card lab-card" data-lab="${id}"><span class="lab-icon">${i}</span><h3>${t}</h3><p>${p}</p></button>`).join('')}</div>`;
  V.features.bindLabs=()=>document.querySelectorAll('[data-lab]').forEach(b=>b.onclick=()=>{const fn=V.labModes[b.dataset.lab];if(!fn)return;fn();const mount=document.getElementById('labMount');if(!mount)return;requestAnimationFrame(()=>{mount.scrollIntoView({behavior:'smooth',block:'start'});mount.focus({preventScroll:true});});});
})(typeof globalThis!=='undefined'?globalThis:window);