(function(root){
  const V=root.VIVA,U=V.ui;
  V.features=V.features||{};
  V.features.vault=()=>`<div class="page-head"><div><h1>Phrase Vault</h1><p>Search, favorite, annotate, and turn your own phrases into practice.</p></div><button class="btn primary" id="addPersonal">+ Personal phrase</button></div><div class="phrase-controls"><input class="input" id="vaultSearch" placeholder="Search Spanish or English"><select class="select" id="vaultCat"><option>All</option>${[...new Set(V.content.phrases.map(w=>w.cat))].map(c=>`<option>${c}</option>`).join('')}<option>Personal</option></select></div><div class="phrase-grid" id="vaultGrid"></div>`;
  V.features.bindVault=function(){ document.getElementById('addPersonal').onclick=personalModal;document.getElementById('vaultSearch').oninput=draw;document.getElementById('vaultCat').onchange=draw;draw(); };
  function draw(){ const q=(document.getElementById('vaultSearch')?.value||'').toLowerCase(),cat=document.getElementById('vaultCat')?.value||'All',all=[...V.content.phrases,...V.store.state.personal.map(x=>({...x,cat:'Personal'}))].filter(w=>(cat==='All'||w.cat===cat)&&(!q||w.es.toLowerCase().includes(q)||w.en.toLowerCase().includes(q)));document.getElementById('vaultGrid').innerHTML=all.map(w=>`<article class="card phrase"><button class="star ${V.store.state.favorites.includes(w.es)?'on':''}" data-star="${U.esc(w.es)}">★</button><b>${w.es}</b><small>${w.en}<br>${w.pron||'Personal phrase'}</small><div class="progress"><i style="width:${U.mastery(w.es)}%"></i></div><div class="row"><button class="pill" data-speak="${U.esc(w.es)}">🔊</button><button class="pill" data-note="${U.esc(w.es)}">📝 Note</button>${w.cat==='Personal'?`<button class="pill" data-train="${U.esc(w.es)}">Train</button>`:''}</div></article>`).join('');U.bindSpeak(document.getElementById('vaultGrid'));document.querySelectorAll('[data-star]').forEach(b=>b.onclick=()=>{const es=b.dataset.star,s=V.store.state;s.favorites=s.favorites.includes(es)?s.favorites.filter(x=>x!==es):[...s.favorites,es];V.store.save();draw();});document.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>noteModal(b.dataset.note));document.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>trainPersonal(b.dataset.train)); }
  function personalModal(){ const d=U.modal(`<div class="modal-head"><h2>Personal Mission Builder</h2><button class="close" data-close>×</button></div><p class="muted">Add something you genuinely want to be able to say. VIVA turns it into recall and listening practice.</p><input class="input" id="personalEs" placeholder="Spanish phrase"><div style="height:8px"></div><input class="input" id="personalEn" placeholder="Meaning"><div class="actions"><button class="btn primary" id="personalSave">Create mission</button></div>`);d.querySelector('#personalSave').onclick=()=>{const es=d.querySelector('#personalEs').value.trim(),en=d.querySelector('#personalEn').value.trim();if(!es||!en)return;V.store.state.personal.push({es,en,pron:'Personal',skill:'Personal',cat:'Personal'});V.store.state.mastery[es]=10;V.store.save();U.closeModal();V.app.render();U.toast('Personal mission created.');}; }
  function noteModal(es){ const d=U.modal(`<div class="modal-head"><h2>Note · ${es}</h2><button class="close" data-close>×</button></div><textarea class="textarea" id="noteText">${V.store.state.notes[es]||''}</textarea><div class="actions"><button class="btn primary" id="noteSave">Save</button></div>`);d.querySelector('#noteSave').onclick=()=>{V.store.state.notes[es]=d.querySelector('#noteText').value;V.store.save();U.closeModal();U.toast('Note saved.');}; }
  function trainPersonal(es){ const w=U.phrase(es),d=U.modal(`<div class="modal-head"><h2>Train · ${es}</h2><button class="close" data-close>×</button></div><div class="prompt">${w.en}</div><input class="input" id="personalTrain"><div class="actions"><button class="btn primary" id="personalCheck">Recall</button><button class="btn secondary" data-speak="${U.esc(es)}">Hear</button></div><div id="personalFeedback"></div>`);U.bindSpeak(d);d.querySelector('#personalCheck').onclick=()=>{const r=V.answerAnalyzer.analyze(d.querySelector('#personalTrain').value,es,{});d.querySelector('#personalFeedback').innerHTML=`<div class="feedback ${r.correct?'good':r.close?'close':'bad'}">${r.correct?'Correct. Your personal phrase got stronger.':r.title+' '+r.message}</div>`;if(r.correct){V.store.state.mastery[es]=V.mastery.clamp((V.store.state.mastery[es]||0)+20);V.store.save();}}; }
})(typeof globalThis!=="undefined"?globalThis:window);