(function(root){
  const V=root.VIVA,U=V.ui;
  const routes=['home','journey','coach','labs','vault','passport','story'];
  V.app={
    render(){
      const s=V.store.state,view=routes.includes(s.view)?s.view:'home';
      document.getElementById('app').innerHTML=`<div class="app-shell"><header class="topbar"><div class="brand">VI<em>VA</em></div><nav class="desktop-nav">${[['home','Home'],['journey','Journey'],['coach','Coach'],['labs','Labs'],['vault','Vault'],['passport','Passport'],['story','Story']].map(([r,t])=>`<button data-route="${r}" class="${view===r?'active':''}">${t}</button>`).join('')}</nav><button class="icon-btn" id="settingsButton">⚙</button></header><main class="main" id="mainView"></main><nav class="mobile-nav">${[['home','⌂','Home'],['journey','◉','Journey'],['coach','✦','Coach'],['labs','⚗','Labs'],['vault','▤','Vault']].map(([r,i,t])=>`<button data-route="${r}" class="${view===r?'active':''}"><b>${i}</b>${t}</button>`).join('')}</nav></div>`;
      const renderer=V.features[view]||V.features.home;document.getElementById('mainView').innerHTML=renderer();this.bindCommon();const binder=V.features['bind'+view[0].toUpperCase()+view.slice(1)];if(binder)binder();U.bindSpeak();
    },
    route(view){V.store.state.view=view;V.store.save();this.render();window.scrollTo(0,0);},
    bindCommon(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>this.route(b.dataset.route));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>this.route(b.dataset.go));document.querySelectorAll('[data-task]').forEach(t=>t.onclick=()=>{const k=t.dataset.task;V.store.state.daily[k]=!V.store.state.daily[k];V.store.save();this.render();});document.getElementById('settingsButton').onclick=()=>this.settings();},
    settings(){const s=V.store.state,d=U.modal(`<div class="modal-head"><h2>Settings</h2><button class="close" data-close>×</button></div>${toggle('Auto-play new Spanish','Hear new phrases automatically.','autoAudio',s.settings.autoAudio)}${toggle('Strict accents','Require accents for full correctness.','strictAccents',s.settings.strictAccents)}<div class="setting"><div><b>Caption fade threshold</b><p>English begins disappearing after this mastery level.</p></div><select class="select" id="fadeSetting" style="width:auto"><option value="60">60%</option><option value="72">72%</option><option value="85">85%</option></select></div><div class="setting"><div><b>Daily goal</b><p>Target minutes per day.</p></div><select class="select" id="goalSetting" style="width:auto"><option value="8">8 min</option><option value="12">12 min</option><option value="20">20 min</option><option value="30">30 min</option></select></div><div class="actions"><button class="btn secondary" id="exportProgress">Export progress</button><button class="btn secondary" id="importProgress">Import progress</button><button class="btn danger" id="resetProgress">Reset</button></div><input type="file" id="importFile" class="hidden" accept="application/json">`);d.querySelector('#fadeSetting').value=s.settings.captionFade;d.querySelector('#goalSetting').value=s.goal;d.querySelector('#fadeSetting').onchange=e=>{s.settings.captionFade=+e.target.value;V.store.save();};d.querySelector('#goalSetting').onchange=e=>{s.goal=+e.target.value;V.store.save();};d.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;s.settings[k]=!s.settings[k];b.classList.toggle('on',s.settings[k]);V.store.save();});d.querySelector('#exportProgress').onclick=()=>{const blob=new Blob([V.store.export()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='viva-progress.json';a.click();};d.querySelector('#importProgress').onclick=()=>d.querySelector('#importFile').click();d.querySelector('#importFile').onchange=async e=>{try{V.store.import(await e.target.files[0].text());U.closeModal();this.render();U.toast('Progress imported.');}catch(err){U.toast('Could not import that file.');}};d.querySelector('#resetProgress').onclick=()=>{if(confirm('Reset every lesson, mistake profile, note, and stat?')){V.store.reset();U.closeModal();this.render();}};}
  };
  function toggle(t,p,k,on){return `<div class="setting"><div><b>${t}</b><p>${p}</p></div><button class="toggle ${on?'on':''}" data-toggle="${k}"><i></i></button></div>`;}
  if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('sw.js').catch(()=>{});
  V.app.render();
})(typeof globalThis!=="undefined"?globalThis:window);